USE [master]
GO

/****** Object:  Database [Adnan_Ebuy]    Script Date: 3/24/2019 10:16:02 PM ******/
CREATE DATABASE [Adnan_Ebuy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Adnan_Ebuy_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Adnan_Ebuy.mdf' , SIZE = 6208KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Adnan_Ebuy_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Adnan_Ebuy.ldf' , SIZE = 6272KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Adnan_Ebuy] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Adnan_Ebuy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Adnan_Ebuy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Adnan_Ebuy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Adnan_Ebuy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Adnan_Ebuy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Adnan_Ebuy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Adnan_Ebuy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET RECOVERY FULL 
GO

ALTER DATABASE [Adnan_Ebuy] SET  MULTI_USER 
GO

ALTER DATABASE [Adnan_Ebuy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Adnan_Ebuy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Adnan_Ebuy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Adnan_Ebuy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Adnan_Ebuy] SET  READ_WRITE 
GO


